### ISSUE TITLE
Please update categories tree and fix a little lag respon on Android.

### ISSUE THREAD

**Issue by DoHaiSon** [g1eny0ung/blog#1]
Hello sir, i'm used ur theme for my blog.
So i saw something that i need ur help:
- Can u update categories menu like menu. We only divide content by categories, it has many disadvantages when there are many topics and posts.
- Theme oke on Desktop, but when open on Android 9 device, and click flip button, a little lag when it flipping. Can u fix this on next commit.

Thanks for reading.

**Comment by DoHaiSon** [comment]
As well as add something like: categories weight to custom order of categories instead order by default.

**Comment by g1eny0ung** [comment]
Sorry for not being able to reply in time. So busy these days. Yes, when there are many categories, the menu does have such problems, I will think about how to solve this problem, thx!

**Comment by g1eny0ung** [comment]
@DoHaiSon After searching, I found that there doesn't seem to be an easy way to define the weight of taxonomy in Hugo.

So I only added a parameter for now to limit the number of categories displayed to solve the problem of a large number of categories.

Here is the doc: https://g1eny0ung.site/hugo-theme-dream/#/params-configurations?id=categorieslimitinheader-6

**Comment by DoHaiSon** [comment]
Thanks for updated.
