### ISSUE TITLE
首页点击具体TAG会展示html代码

### ISSUE THREAD

**Issue by jiaxuyang** [g1eny0ung/blog#10]
复现：
https://g1en.site/
首页点击任意一个tag
![image](https://github.com/g1eny0ung/blog/assets/14369148/a93b8d96-2638-42f3-8a25-d8edcb7ab835)

预期：正常跳转页面
实际：
![image](https://github.com/g1eny0ung/blog/assets/14369148/7d6c2a3c-0126-4df9-8d3e-00b54a3f0005)

**Comment by g1eny0ung** [comment]
https://github.com/g1eny0ung/hugo-theme-dream/commit/5796a28759eb5fe89e2e24e8fbb41a0c0cfe39c1 我刚才修复了，是因为我放置了一个空的 `term.html` 文件在 `tags` 下面，之前这个空的文件被忽视了，可能最近的 Hugo 版本会检测到它。非常感谢提醒。❤️
