### ISSUE TITLE
I couldn't upload it to blogger🥺🥺🥺

### ISSUE THREAD

**Issue by Dhatchu08** [g1eny0ung/blog#3]
I love your theme a lot. But I couldn't upload it to blogger. Please do something🥺
![Capture](https://user-images.githubusercontent.com/67735359/86342047-b1985480-bc74-11ea-9f52-0d2faee2a838.PNG)

**Comment by g1eny0ung** [comment]
Sorry for the delayed reply. I already check the HTTP links in the dream theme. Seems that all HTTP links only occurred in docs.

**Comment by Dhatchu08** [comment]
Ohh okay bro. I will try editing the code. Thanks☺.
